name: Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build

      - name: Test pty
        run: |
          sshpass -P'Password: ' -pfoobar node ./examples/getpass.js

      - name: Run tests
        run: npm test

