name: Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run tests
        run: |
          ls -lh /dev/tty
          if [ -t 0 ]; then
            echo "stdin is a terminal"
          else
            echo "stdin is NOT a terminal">&2
          fi
          export TERM=xterm-256color
          npm test

